### PR TITLE
Fix for missing custom classname on the frontend

### LINKED ISSUE #126: Class not applied to Safe SVG Icon block in front end
### Describe the bug

Custom classes applied are not saved for front end in Safe SVG Icon block. Works properly in editor.

### Steps to Reproduce

1. Insert Safe SVG Icon block
2. Apply a custom class to block
3. Save page / post
4. In front end no custom classes are present

### Screenshots, screen recording, code snippet

Editor, block has `.large-text-center` correctly applied:

image

Front end, custom class is not present:

image

### Environment information

_No response_

### WordPress information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by bmarshall511**
### Description of the Change

Fixes the missing custom classname on the frontend. It was being applied in the editor, but not when rendering on the front.

Closes #126 

### How to test the Change

1. Insert Safe SVG Icon block
2. Apply a custom class to block
3. Save page / post
4. View source in the frontend to verify the class has been applied

### Changelog Entry

> Fixed - Fix for missing custom classname on the frontend

### Credits

Props @bmarshall511 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).

### CODE REVIEW

File: includes/blocks/safe-svg/register.php [hunk 1]
```diff
@@ -68,10 +68,11 @@ function render_block_callback( $attributes ) {
 		'safe_svg_inline_markup',
 		sprintf(
 			'<div class="safe-svg-cover" style="text-align:%s">
-				<div class="safe-svg-inside %s" style="width: %spx; height: %spx;">%s</div>
+				<div class="safe-svg-inside %s%s" style="width: %spx; height: %spx;">%s</div>
 			</div>',
 			$attributes['alignment'] ?? 'left',
 			$class_name,
+			isset( $attributes['className'] ) ? ' ' . $attributes['className'] : '',
```
Comment (Sidsector9) [inline includes/blocks/safe-svg/register.php]: Thanks for the PR @bmarshall511 

I noticed that none of the outputs are escaped. This line in particular can be escaped using `esc_attr()`.
I was able to inject JavaScript through the CSS classes field.

Add this string as the CSS class `"onclick="alert('hello')"` as shown in the image:

Screenshot 2023-06-29 at 2 19 46 PM

Visit the frontend and click the SVG, observe the `alert()`.

https://github.com/10up/safe-svg/assets/17757960/bfa8b8bb-6ab9-48b8-9f4a-ce83e2174476


Please let me know your thoughts on this.

**Review by Sidsector9 — CHANGES_REQUESTED** [review]

File: includes/blocks/safe-svg/register.php (hunk 1 above)
Comment (bmarshall511) [reply includes/blocks/safe-svg/register.php]: @Sidsector9 My mistake & thanks for catching that! I've updated the code accordingly.

**Review by dkotter — APPROVED** [review]
