### PR TITLE
Ensure our width and height variables exist before we use them

### LINKED ISSUE #54: Undefined variable: viewbox_width in safe-svg.php#L507
### Describe the bug

Today I imported a large about of files and SVG's from a `prod`-site to a `local`-site.
During that process the plugin gave some warnings. Most of them where:

> Notice: Undefined variable: viewbox_width in /Users/username/local-sites/domain/app/public/wp-content/plugins/safe-svg/safe-svg.php on line 507

[safe-svg.php#L507](https://github.com/10up/safe-svg/blob/develop/safe-svg.php#L507)

### Steps to Reproduce

Unknown. I assume it's because one or more svg's is missing a viewbox attribute.

### Screenshots, screen recording, code snippet

Screenshot 2022-04-13 at 15 28 36(private information obfuscated)

[safe-svg.php#L507](https://github.com/10up/safe-svg/blob/develop/safe-svg.php#L507)

### Environment information

Device: MacBook Pro M1
OS: macOS Monterey 12.3.1
Browser: Chrome 100.0.4896.75 (Official Build) (arm64)

### WordPress information

`
### wp-core ###

version: 5.9.3
site_language: nl_NL
user_language: nl_NL
timezone: Europe/Amsterdam
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: undefined
environment_type: production
user_count: 6
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/customer/www/domain.tld/public_html
wordpress_size: 52,16 MB (54696619 bytes)
uploads_path: /home/customer/www/domain.tld/public_html/wp-content/uploads
uploads_size: 266,52 MB (279462198 bytes)
themes_path: /home/customer/www/domain.tld/public_html/wp-content/themes
themes_size: 118,94 MB (124716088 bytes)
plugins_path: /home/customer/www/domain.tld/public_html/wp-content/plugins
plugins_size: 79,97 MB (83857959 bytes)
database_size: 41,70 MB (43728896 bytes)
total_size: 559,29 MB (586461760 bytes)

### wp-active-theme ###

name: PRIVATE/OBFUSCATED
version: 1.0.3
author: Pronamic
author_website: https://www.pronamic.eu/
parent_theme: none
theme_features: core-block-patterns, block-templates, widgets-block-editor, automatic-feed-links, html5, title-tag, custom-logo, align-wide, menus, post-thumbnails, editor-style, widgets
theme_path: /home/customer/www/domain.tld/public_html/wp-content/themes/theme
auto_update: Uitgeschakeld

### wp-themes-inactive (2) ###

Twenty Twenty-One: version: 1.5, author: the WordPress team, Auto-updates uitgeschakeld
WedWiki: version: 1.0.79, author: Pronamic, Auto-updates uitgeschakeld

### wp-mu-plugins (1) ###

InfiniteWP - Client Loader: author: Revmakx, version: (undefined)

### wp-plugins-active (15) ###

ACF Content Analysis for Yoast SEO: version: 3.0.1, author: Thomas Kräftner, ViktorFroberg, marol87, pekz0r, angrycreative, Team Yoast, Auto-updates uitgeschakeld
Advanced Custom Fields PRO: version: 5.12.2, author: Delicious Brains, Auto-updates uitgeschakeld
Akismet Anti-Spam: version: 4.2.2, author: Automattic, Auto-updates uitgeschakeld
Gravity Forms: version: 2.6.1, author: Gravity Forms, Auto-updates uitgeschakeld
InfiniteWP - Client: version: 1.9.6, author: Revmakx, Auto-updates uitgeschakeld
Members: version: 3.1.7, author: MemberPress, Auto-updates uitgeschakeld
Post Types Order: version: 1.9.8, author: Nsp Code, Auto-updates uitgeschakeld
Pretty Links: version: 3.2.4, author: Pretty Links, Auto-updates uitgeschakeld
Pronamic Client: version: 1.9.4, author: Pronamic, Auto-updates uitgeschakeld
SiteGround Optimizer: version: 7.0.9, author: SiteGround, Auto-updates uitgeschakeld
SiteGround Security: version: 1.2.7, author: SiteGround, Auto-updates uitgeschakeld
SVG Support: version: 2.4.2, author: Benbodhi, Auto-updates uitgeschakeld
User Switching: version: 1.5.8, author: John Blackbourn & contributors, Auto-updates uitgeschakeld
Yoast SEO: version: 18.5.1, author: Team Yoast, Auto-updates uitgeschakeld
Yoast SEO Premium: version: 18.3, author: Team Yoast, Auto-updates uitgeschakeld

### wp-plugins-inactive (1) ###

Casino Features: version: 1.0.0, author: Author Name, Auto-updates uitgeschakeld

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Niet beschikbaar
imagemagick_version: Niet beschikbaar
imagick_version: Niet beschikbaar
file_uploads: File uploads is turned off
post_max_size: 256M
upload_max_filesize: 256M
max_effective_size: 256 MB
max_file_uploads: 20
gd_version: 2.2.5
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.27

### wp-server ###

server_architecture: Linux 3.12.18-clouder0 x86_64
httpd_software: Apache
php_version: 7.4.28 64bit
php_sapi: cgi-fcgi
max_input_variables: 3000
time_limit: 120
memory_limit: 768M
max_input_time: 120
upload_max_filesize: 256M
php_post_max_size: 256M
curl_version: 7.66.0 OpenSSL/1.1.1n-fips
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.7.32-35-log
client_version: mysqlnd 7.4.28
max_allowed_packet: 33554432
max_connections: 500

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/customer/www/domain.tld/public_html/wp-content
WP_PLUGIN_DIR: /home/customer/www/domain.tld/public_html/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 768M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Ongedefinieerd
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by dkotter**
### Description of the Change

In #43 we slightly changed up how we determine the dimensions of an SVG image, to fix a previous bug but to also preserve backwards compat. There's a minor bug in the fix though, where if an SVG doesn't have the `viewbox` attribute set or doesn't have the `height` and `width` attributes set and a site is using the newly introduced filter, a PHP warning will be output because we try and use a variable that isn't defined.

This PR fixes that by ensuring the attributes we want are set before we use them. We also add better fallback handling so if, for instance, `viewbox` attributes aren't set we still try to use the `height` and `width` attributes (and vice versa, if the new filter is used).

### Alternate Designs

None

### Possible Drawbacks

None

### Verification Process

Prior to this fix, test rendering an SVG that doesn't have the `viewbox` attribute set and notice PHP warnings are displayed (assuming you have debug turned on).

After this fix, those warnings should go away.

In either case, the actual SVG output should be the same.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Changelog Entry

> Fixed - Ensure our height and width attributes are set before using them

### Credits

Props @dkotter, @r8r

### CODE REVIEW

File: safe-svg.php [hunk 1]
```diff
@@ -500,12 +500,24 @@ protected function svg_dimensions( $svg ) {
...
-                    $width  = $viewbox_width;
-                    $height = $viewbox_height;
+                    if ( isset( $viewbox_width, $viewbox_height ) ) {
+                        $width  = $viewbox_width;
+                        $height = $viewbox_height;
+                    } elseif ( isset( $attr_width, $attr_height ) ) {
+                        $width  = $attr_width;
+                        $height = $attr_height;
+                    }
                 }
```
Comment (jerturowetz) [inline safe-svg.php:521]: This is awesome. I'm assuming we can't use php 7 stuff like the null coalescing operator to improve readability?

File: safe-svg.php [hunk 2]
```diff
@@ -500,12 +500,24 @@ protected function svg_dimensions( $svg ) {
...
 
                 if ( ! $width && ! $height ) {
```
Comment (jerturowetz) [inline safe-svg.php:523]:
```suggestion
                if ( ! $width || ! $height ) {
```

**Review by jerturowetz — CHANGES_REQUESTED** [review]
Just a small change as I think the function should return false if either `$width` or `$height` are missing

File: safe-svg.php (hunk 2 above)
Comment (cadic) [reply safe-svg.php:523]: The current condition requires both `$width` and `$height` to be non-zero (as they initially set at [:471](https://github.com/10up/safe-svg/pull/51/files#diff-05bf19b873cfb6358cd7c239366db6675635bf4b03a4b56353102e359d5c2859L471)). The suggested condition will drop this to "any is zero" which will return false for SVG with zero size of one side.

Even if this is not related to the current PR, probably needs improvements:
- `$width` and `$height` initial assign to `false` at [:471-472](https://github.com/10up/safe-svg/pull/51/files#diff-05bf19b873cfb6358cd7c239366db6675635bf4b03a4b56353102e359d5c2859L471)
- Checking any or both are `false` at [:511](https://github.com/10up/safe-svg/pull/51/files#diff-05bf19b873cfb6358cd7c239366db6675635bf4b03a4b56353102e359d5c2859L511)

**Review by cadic — APPROVED** [review]
Thank you for updating this @dkotter , LGTM

File: safe-svg.php (hunk 2 above)
Comment (cadic) [reply safe-svg.php:523]: @jerturowetz The current condition expects both `$width` and `$height` to be non-zero (as they initially set at :471).

The suggested change will drop this to "any is zero" condition which will return cause function return false in case of one side SVG is zero.

File: safe-svg.php (hunk 1 above)
Comment (dkotter) [reply safe-svg.php:521]: I do believe our minimum PHP version is 7, so we could use the null coalescing operator here, though I guess I'm not sure where that would go? Happy to look at changing this if you have a suggestion on how this could be done better.
